### ISSUE TITLE
Why does this happen?

### ISSUE THREAD

**Issue by LilFoxProgramer** [xlang-ai/xlang#4]
![image](https://github.com/xlang-ai/xlang/assets/86305196/6401a378-8c66-4a7d-8550-1f707e3ef72d)

The code generated by the agent is actually runable.

**Comment by koalazf99** [comment]
I think this can be caused due to some server issues, we will look into it.
Thank you @LilFoxProgramer for letting us know~😊😊

---
p.s. I tried to re-start the server, and now looks good from my side, let me know if there remains further problems

**Comment by LilFoxProgramer** [comment]
It seems to be back to normal, thank you for your quick response
